version: '3.7'

services:
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
    env_file:
      - .env
    ports:
      - 8000:${APP_PORT}
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: